@startuml
left to right direction
actor Utilisateur

actor IA

rectangle "StageAI" {
  Utilisateur -- (S'inscrire)
  Utilisateur -- (Se connecter)
  Utilisateur -- (Générer un texte IA)
  Utilisateur -- (Générer une image IA)
  Utilisateur -- (Consulter l'historique)
  Utilisateur -- (Utiliser le chat IA)
  Utilisateur -- (Se déconnecter)
 
  (Générer un texte IA) ..> IA : « Prompt »
  (Générer une image IA) ..> IA : « Prompt »
  (Utiliser le chat IA) ..> IA : « Message »
}
@enduml
